name = "Samitha Hemantha"
print("S" in name)
print("S" not in name)
print(name[0])
print(name[-1])
print(name.upper())
print(name.lower())
print(name.title())
print(name.capitalize())
print(name.find('a'))
print(name.find('a',3))
print(name.center(20))
print(name.ljust(20))
print(name.rjust(20))
print(name.center(20,"-"))
print(name.endswith("h"))
print(name.replace("a","A"))
print(name.split(" "))